---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

bases:
  - ../../base

patchesStrategicMerge:
  - config.yaml
  - ingress.yaml
  - certificate.yaml

patches:
  - target:
      kind: Ingress
      name: ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: honzas.garden
      - op: replace
        path: /spec/rules/1/host
        value: api.honzas.garden
