---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.yaml
  - ingress.yaml
  - certificate.yaml
  - config.yaml # configMapGenerator has not unique name :/

  - api/deployment.yaml
  - api/network-policy.yaml
  - api/service.yaml

  - runner/deployment.yaml
  - runner/network-policy.yaml
  - runner/service.yaml

  - web/deployment.yaml
  - web/network-policy.yaml
  - web/service.yaml

  - mysql/deployment.yaml
  - mysql/network-policy.yaml
  - mysql/service.yaml
  - mysql/storage.yaml
