definitions:
  handler.POSTEntity:
    properties:
      peripheryId:
        example: 4
        type: integer
      value:
        type: number
      workId:
        example: 77
        type: integer
    required:
    - peripheryId
    - value
    - workId
    type: object
info:
  contact:
    email: info@jantuzil.cz
    name: Jan Tuzil
    url: https://jantuzil.cz
  description: Mmmmm it tastes so good..
  title: Mung bean sprout garden REST API :))))
  version: "1.0"
paths:
  /api/v1/measurement:
    post:
      consumes:
      - application/json
      parameters:
      - description: Measurement informations
        in: body
        name: string
        required: true
        schema:
          $ref: '#/definitions/handler.POSTEntity'
      - description: Request signature
        in: header
        name: X-Signature
        required: true
        type: string
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server&nbsp;Error
      summary: Measurement result
swagger: "2.0"
