---
apiVersion: batch/v1
kind: Job
metadata:
  name: rasp-deploy
  namespace: prod
spec:
  template:
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: rasp-deploy
          image: ${IMAGE_RASP_DEPLOY}
          imagePullPolicy: Always
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: API_URL
            - name: API_SIGN_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: API_SING_KEY
            - name: MYSQL_DSN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MYSQL_DSN
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SENTRY_DSN
      restartPolicy: Never
  backoffLimit: 1
